AWSTemplateFormatVersion: "2010-09-09"
Description: "Einfaches EC2-Deployment"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  ImageId:
    Type: String
    Default: ami-0cbcbef074db940ca
  SecurityGroupId:
    Type: String
    Default: sg-0a26919cb467cc0fe

Resources:
    EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      SecurityGroupIds: !Ref SecurityGroupId
      # Optional: UserData für automatische Befehle beim Start
      # UserData: !Base64 |
      #   #!/bin/bash
      #   yum update -y
      #   echo "Hello from CloudFormation" > /var/www/html/index.html

Outputs:
  InstanceId:
    Description: ID der erstellten Instanz
    Value: !Ref EC2Instance
  PublicIP:
    Description: Öffentliche IP-Adresse (falls öffentliches Subnetz)
    Value: !GetAtt EC2Instance.PublicIp




