AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template zum automatischen Erstellen einer EC2-Instanz"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: "EC2 Instanztyp"
    
  ImageId:
    Type: String
    Default: ami-0cbcbef074db940ca
    Description: "AMI ID für die EC2-Instanz"
    
  SecurityGroupId:
    Type: String
    Default: sg-0a26919cb467cc0fe
    Description: "Vorhandene Security Group ID"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      SecurityGroupIds:
        - !Ref SecurityGroupId

Outputs:
  InstanceId:
    Description: "ID der erstellten EC2-Instanz"
    Value: !Ref EC2Instance
    
  PublicIP:
    Description: "Öffentliche IP-Adresse der EC2-Instanz"
    Value: !GetAtt EC2Instance.PublicIp






